system:
  port: ":8088"

jwt:
  secret: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImFkbWluIjp0cnVlfQ.n-qvhsRi6C0zBGcKrMGv-qSZGUUssXTTbICvENxqDCjCL2ejSt62uTwemHZe4pLI_sNSr7FWEI2MKlqequemeg"
  expiration: 7200  # // 单位：秒

cors:
  enable: true
  allowedOrigins:
   - "localhost:8080"
   - "127.0.0.1:8080"
   - "demo-mysql.10.179.25.1.nip.io"
  # 设置Access-Control-Allow-Origin的默认的值
  defaultOrigins: "http://demo-mysql.workbench/"
  accessControlAllowCredentials: "true" # 是否允许浏览器发送跨域请求时携带认证信息（如Cookies和HTTP认证）
  accessControlAllowHeaders: "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id" # 指定服务器接受哪些头部字段作为跨域请求的一部分
  accessControlAllowMethods: "POST, GET, OPTIONS,DELETE,PUT" # 指定服务器允许的HTTP请求方法
  accessControlExposeHeaders: "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, New-Token, New-Expires-At" # 指定哪些HTTP头部可以作为响应的一部分暴露给外部  