system:
  port: ":8080"

jwt:
  secret: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImFkbWluIjp0cnVlfQ.n-qvhsRi6C0zBGcKrMGv-qSZGUUssXTTbICvENxqDCjCL2ejSt62uTwemHZe4pLI_sNSr7FWEI2MKlqequemeg"  # 建议只保存密钥，不要存 token 全文
  expiration: 7200  # 单位：秒

log:
  level: "debug"    # 支持：debug、info、warn、error
  format: "console" # 可选：console（开发）或 json（生产）
  file: ""          # 可选：写入文件的路径（默认空，即只输出到控制台）

cors:
  enable: true
  allowedOrigins:
    - "http://localhost:9528"
    - "http://127.0.0.1:8080"
    - "http://kubeants-apiserver.kubeants-system"
    - "http://172.17.142.147:30001"
  defaultOrigins: "http://172.17.142.147:30001"  # 默认允许的 Origin，建议开发环境使用 localhost
  accessControlAllowCredentials: "true"
  accessControlAllowHeaders: "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id"
  accessControlAllowMethods: "POST, GET, OPTIONS, DELETE, PUT"
  accessControlExposeHeaders: "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, New-Token, New-Expires-At"

# 权限控制配置：注：可以使用 * 通配符，表示所有 resource 或 verbs。
authz:
  exemptResources:
    - group: ""
      version: "v1"
      resource: "namespaces"
      verbs: ["get", "list"]
    - group: "workspace.kubeants.io"
      resource: "*"
      verbs: ["get", "list"]
    - group: "userbinding.kubeants.io"
      resource: "*"
      verbs: ["get", "list"]
    - group: "rbac.kubeants.io"
      resource: "roletemplates"
      verbs: ["get", "list"]

