---
# kubectl -n kubeants-system create secret generic  kubeconfig --from-file=config=.kube/config
# apiVersion: v1
# data:
#   config: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNdmFrTkRRV1ZoWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkpNVTFFVVhsTlJFRTBUVVJOZUUweGIxaEVWRTB4VFVSUmVFOUVRVFJOUkUxNFRURnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVFdWMkNtbEljakpZUVZwR1dEUjZTSFJOT1hOeVNtVlllRTkxWlRCeE5IaGxibTU1ZGxOR2JUZDJaV2RZU0RsM2NrMVVkMHQ1Tkdaa2JIWm9ZV2xCV1ZWaGVGY0thRUpZV21KaGVUSkJhRmQ0Tm1sRU5uZ3djbWRwYVZCRVdVb3JaU3Q1UW5Cc2FURjZTMWhOYkUwM2NqVlJUbGc0Y1d0dGJXeGhVVU50Y2sxblFVOVZUd3A1TWxBeU1YY3hTRGRzYVRaNVMxWmpOVmM1VFU1VVRXRnhTbTFITHpOSVRrRmhSRTlKYUdWR1RHRldSbU13Tld3emVEbFdOVzFQZUhGTU5rZDZUbFJxQ2pSeWRYVm5MMnhZYkhGWk5WSXlWa1JYWlRCSGVVeHNNbUkyUjIxT1dqSjJNWEU0ZUZOeGVGbHJTMGwxTkZKc1lYcFplVlZwTVVrNVVrbHlia0puTW1RS2FIRlFlRkYwZUcxSldUZFdWSGhpUlZsRVZsWnRZMFJFV1V3NU9IQkpVRGwzVlhOMlNISjNUVVZtUTJ0a1dqRlRXSGRoVDFoeWRtaGFSRkp0TmxCdVJBbzRURk5LY0hWak5IUm1PREpIYjJKc2VEVnpRMEYzUlVGQllVNWFUVVpqZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWlFiRkl6YUhaYU5GTk5ObFUzY2tKbWFWUXhTMGMzVjFGU2RTOU5RbFZIUVRGVlpFVlJVVThLVFVGNVEwTnRkREZaYlZaNVltMVdNRnBZVFhkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCU2xGUk5qUjBWR0ZsUkdWT2QyTkhhVGcwTndwbVNYYzJSR0o1VHlzeGFHMURSRGMyVm5wdlN6SjVSamRFUnpWTE4xZzJOMWN4UlRORlVITnhZMUpuTUhOb1ZERlZjMVJrYWpOeFRtc3ZSMUl3ZVZoUUNrVndlREYyY2xGRlFubGhSSE4zVUhCUWJHNHhiMk40Y0ZBNE5TOUNlakYxYkhvNVlVSk5NblZhUWl0NFpXcEpjVVl6UTBwRldtTm9SRWRQTWpsdlNXd0tTbkZ5Y21wT1dqRnRSblpJTld0Uk5HMUtWVU5FTTNwMmIzWXhjbFZTTTFjeVl6SnlXbmhqVW5VeGRFMUtOVGQ2YTBjMWRHMTFkalJLWjBoNk9FeDJXQXA0TkdwaFdsSmhkWFp3YWpkQ1pqSjRVbXhMUjNwV1dUQkdjMlZTUmtoSVZqUXplV3h6VUU0MGNEQTRaRmhEYlRGNWR6ZExTRGxqTkRVNFUyNWpUazh2Q201SWJXTkdUbkY1ZDNBNE9FZEtjR1pJZWxWMWVXMU5XbXMyYVRGbVkwODNObnBsTTNoelowaEJObFp5VVRCVVYxZFNVVU0xY2tNMk1qUTRZVGxSV0d3S0wxSXdQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBzZXJ2ZXI6IGh0dHBzOi8vMTI3LjAuMC4xOjMzMjEzCiAgbmFtZToga2luZC1rOHMxCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBraW5kLWs4czEKICAgIHVzZXI6IGtpbmQtazhzMQogIG5hbWU6IGtpbmQtazhzMQpjdXJyZW50LWNvbnRleHQ6IGtpbmQtazhzMQpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGtpbmQtazhzMQogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNhdGUtZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkpWRU5EUVdkdFowRjNTVUpCWjBsSldqTjVkVlV2UlRWUGRITjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRHVkVWVVRVSkZSMEV4VlVVS1FYaE5TMkV6Vm1sYVdFcDFXbGhTYkdONlFXVkdkekI1VGxSQk1FMXFRWGRQUkVGNlRWUk9ZVVozTUhsT2FrRXdUV3BCZDA5RVFYcE5WRkpoVFVSUmVBcEdla0ZXUW1kT1ZrSkJiMVJFYms0MVl6TlNiR0pVY0hSWldFNHdXbGhLZWsxU2EzZEdkMWxFVmxGUlJFVjRRbkprVjBwc1kyMDFiR1JIVm5wTVYwWnJDbUpYYkhWTlNVbENTV3BCVGtKbmEzRm9hMmxIT1hjd1FrRlJSVVpCUVU5RFFWRTRRVTFKU1VKRFowdERRVkZGUVhacEsyNURNV3REWWpkV1RqWk1ibU1LTjJGa1VVZFlZVzFEYTB4T1pFVkpXVGcyVFUxQmMwSk1PSHBSYm1sVGJsYzBUMjEyVVd4alJHUnRWQzlqUm00M2RqTkxZMFJsSzNrNFVsbzNSRkJVUkFvek1raHRRVloxTlROa1pFbGFlbWhhVGpBdlFqUkdSV1J2U25NNE0ybFRhSFptWkdKWlEyNUphMkp4T1ZRMVQwMW9aRTlYZW5wUFkxSllPWE55VTB4bkNtRTJibW8yTkVNdk5VeHhjRU54ZW1aRE5qbFdjV0kwVWpWQ01qWmpabFV3Um1SUE9EUjBVbGhOTW10d1VWWnFjVFZZTlVoMVNuTldaMDR5YzJwWlNrRUtORzQxUkRWR2VURTBMMEZsVUVoQ1NucFdjM0pZUVdWQ2NUbHpaVUZTTUVGRFpVZE1NM2xITWtoSVJGUXdZVXRpU2tkSE5GZG9ObWhIYzIxNGVXUnpOUW80ZW5kMGQzTlNUVTFQT1VWMVVHTTNLMHBLUTBGNWNteGhjemxaY1ZabGQybExhR1IwUjBweU16ZFRaSE01UkM4MVExaDBVa014WXpGd1RGcFFNVnBOQ2swNU5DdDRkMGxFUVZGQlFtOHhXWGRXUkVGUFFtZE9Wa2hST0VKQlpqaEZRa0ZOUTBKaFFYZEZkMWxFVmxJd2JFSkJkM2REWjFsSlMzZFpRa0pSVlVnS1FYZEpkMFJCV1VSV1VqQlVRVkZJTDBKQlNYZEJSRUZtUW1kT1ZraFRUVVZIUkVGWFowSlVOVlZrTkdJeVpVVnFUMnhQTm5kWU5HczVVMmgxTVd0RllncDJla0ZPUW1kcmNXaHJhVWM1ZHpCQ1FWRnpSa0ZCVDBOQlVVVkJkakl2V1had1IySTNZMFV5Vm1oSGNFNXlhV0pJWTJKQ05IQXhXSGxPUldWRGJ6WTBDbXAxUzFwVFp6TXZiMWd2WTFremQweHViRkZoYkROQldDdG5lRXhVVEdwc01qSlpZMk5MUVRONGRYVllNVXhMUm14aWVDdHBURUZuVVVGdlNFdGpNMHNLT0d3MWRXNWpUR1p5UmpkdGVHaHlPR3R0UW1oek9WbHpWWFJYUkd4UlN6ZHdLeTkyTWtZek1tNXRORk5VVjJKa09XeFdZbXBaTUVkdk5qRklkVEo2VFFwbVNrVnlPR3hrWTFWR056aGpXRk5xVFRkelpqSnlTRGhZYld0UldHSmFZV294Wm1WeFFVRk9TakpZVUhod1l6aFFTMUJTTldGM1IycFZSRVpIUWpSbkNqaHJaM0JCYTFSbFVHeDVOR1ZoZG1GT2ExUTJNRXBHYUhZNVRVWjFSV1J6TTBvd1p6QklNMmxXY21KQk9HTTFPRUY1V0RGclYwaHFTWE5hUTB4NmJYTUtiR0p2YWpWcU5tSmFNSFJqUW1oQlMySnBRbTlRUjFSdlZ6SlVaemczUTJsUVVWbFNURGw2VldGdEsycHdSbGxyV0hjOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIGNsaWVudC1rZXktZGF0YTogTFMwdExTMUNSVWRKVGlCU1UwRWdVRkpKVmtGVVJTQkxSVmt0TFMwdExRcE5TVWxGYjNkSlFrRkJTME5CVVVWQmRta3Jia014YTBOaU4xWk9Oa3h1WXpkaFpGRkhXR0Z0UTJ0TVRtUkZTVms0TmsxTlFYTkNURGg2VVc1cFUyNVhDalJQYlhaUmJHTkVaRzFVTDJOR2JqZDJNMHRqUkdVcmVUaFNXamRFVUZSRU16SkliVUZXZFRVelpHUkpXbnBvV2s0d0wwSTBSa1ZrYjBwek9ETnBVMmdLZG1aa1lsbERia2xyWW5FNVZEVlBUV2hrVDFkNmVrOWpVbGc1YzNKVFRHZGhObTVxTmpSREx6Vk1jWEJEY1hwbVF6WTVWbkZpTkZJMVFqSTJZMlpWTUFwR1pFODROSFJTV0UweWEzQlJWbXB4TlZnMVNIVktjMVpuVGpKemFsbEtRVFJ1TlVRMVJua3hOQzlCWlZCSVFrcDZWbk55V0VGbFFuRTVjMlZCVWpCQkNrTmxSMHd6ZVVjeVNFaEVWREJoUzJKS1IwYzBWMmcyYUVkemJYaDVaSE0xT0hwM2RIZHpVazFOVHpsRmRWQmpOeXRLU2tOQmVYSnNZWE01V1hGV1pYY0thVXRvWkhSSFNuSXpOMU5rY3psRUx6VkRXSFJTUXpGak1YQk1XbEF4V2sxTk9UUXJlSGRKUkVGUlFVSkJiMGxDUVVJeFMwZ3pTelk0V1c5amNGQlFOd3BqT0M5U00xbzRaVk0zU0RJeVkyUlhlWEJ5ZVN0Rk1sRkxaVWsxYmxGRlpIaFhOemMzYW1KTlUyTmpOVUpNU0dJeVl6WkNTM2hHYlZsbGRVcEtPR2N5Q2tKa2FHOU1iRVF4VUVkdGVURjJOakpwWkRkbU1VbzNhMUI1YWxZek5HcHBiMVp2ZEU1NFFsaFFkMFpoWm1ZNE9GaFFOMkpQUkZkUE5FUnJMM2cwTDJVS1pVTjBPR3BhU21WVlN6ZzRTUzgxTVRSNEwyTnFPV1pHV1hWSU4yZG1UMmd4Y1RSSk9WcHpSVmQzZEZaSFdFTmpMM1JyYVU1TWMyUk9UR1J2TlVWTFRBb3ZWa1JzWjJ4SUwzaFdMMlZEZEdvMk5tZFRWRU50V0hsc1QxaFhkMWhYV0RKaVdIVnFURzVpU21OVWMxZDZaR0p4ZFU1MWFEVkZhV3RHVXpnM1JrY3lDa2g2WlVvNU1HVndWVzF6VFUxa2NqRTFkMmhVY1ROa1QyVjFWRUptU3pSek5EaENUbFpEU1c0NFRHdFNSR0pQZHpOemRtczBkSHB2TTJWcFJFSnVTRk1LU1VkMVYycE5hME5uV1VWQk4waDNiMW8xZHpCcFUycHNaa1pWYkROS1VqZzBSbGRJV1hWWWJtUjVTa2w1ZFdwWFNFcDNOaTlRUkdaWGJHbGtaRFpRWWdwdlZWb3ZkaTh3YTBad2VtRkplWGhJZFU5REswcExkak01Y2tWellsaEJUVVp3UTBrNWIzQmlVbVZ1YTFCQmVYQjVTR0paTWxJMVVDdDNUMFUyWlVKa0NqQk5iM2xwWnpGVlYyVkZSWEk0UTJaWFNIWlhNRGxRV2pCR1lWUldUelIzZVUxRlowNUlWbGxHUW5rNVZqTlROVmRVZWxwdFZWVkRaMWxGUVhwbFJuQUtibVo0YVVSMWVIWkhRMlpyUzJoNE5USkdZVkZhY1VScVZ6ZEtjbVowTVVFMFZqTnZSbTVGY1c5elFXVXdSa2hHU2pWQmQybHpWMUZGTVRBNFZFbFZNUXBGWnpORWFWSk9Na1JYTDNWV1owUlVjV2d3YjFSSmJGTXljMUJOWjBGMlVHbHBXQ3RSYkRGRll5OWxNRkJxVkVFeFlUTnFRMHQwYkZWSmEwdzBjRGMwQ2pNd1RHdHFVRmRRUVVwNVMwTjZOMEZHWmtSMmNqaHBWRTU0WVZodWNVcHNabnA0VjNsd2MwTm5XVUZ4WjJSaGVHRlFOVFJsVVZadE5UbGpObGwxV21ZS1dFbENUbGx2TTAxbFJHdHNXRGw1T0c0NGFIRnNkRVpQTmtGaVJqZHZiMWd6ZUdkMldtc3dTMVV6T1ZOUGVUbGFTaXQ1Um05MlQySlJRbGRCVW14bGJBbzFjWG96ZHpjM1RWQnNTbk5EVFhGeU5HUkVkMnhsV2tOa1JYUTNlbTU1VDJaM2JTdHFjemRQY1ZGbGVXNDJhMFYxY0ROUGVscEhiRkpUY1U5YVdrbFlDbEUzSzB0TWJERTJiaTh2V1hKSU5UQmlPU3RrUlZGTFFtZFJRMlV5VFRKS2NFMUlkbkU0UzI1cE5XWkRWMmRuTUhZNE1WbE5ZMmhhTlhCaFJEUnhaamtLWld4MmIyWk9XV1JxYTJZMFExTTRjSE5HYlZSeFNYcGhUUzlUYWxGYUwwb3hlVGRJTkRKclVsRjNlRXc1VVZaaE1tNWFUMWg1UnpkUmNHcFdUSE5sY0FwWGJHdE1NRlJTVVcxWmVrczVhRGRYWm5aNVRtOTBhR1ozS3pKVmJ6TXhNMjVSUVVWT2FUVnZiRlkzTlVGRGFIRm9WMUZhV2pWTlYxUlBjMk0zVlZkTkNsaDJla1ZCZDB0Q1owTk5LMjR6VkZFeGVuWkNkRmx4VG5OS2NXVXpOa3BCUjBwWmN5czFWakpNTVZoS01GWXlMMjVoWTNWR1pVaEVRemQwS3l0dlZISUtPR1JMVDI5eWFYZFRkbVJ2YjJwd09XdHZjR2d6VFM4NVlrTm9RekJXVjJWUlEzTXplbEEzUkdOa2JtczJjbTB3TkhWMU9WaFJTMjh2TTNsYVpITlZVQXBRV0V4SVlUaFVhRkpzUVRWak9EUnhRamg2TmtKeFlVbGxWWFJKU0ZGa2NXTjNTRTVCUVRKdE1Fd3pZWGM1TjFaR1VWcEpDaTB0TFMwdFJVNUVJRkpUUVNCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2c9PQo=
# kind: Secret
# metadata:
#   name: kubeconfig
#   namespace: kubeants-system
# type: Opaque
---
# kubectl create cm kubeants-apiserver -n kubeants-system --from-file=config.yaml
apiVersion: v1
data:
  config.yaml: |
    system:
      port: ":8080"

    jwt:
      secret: "xxx"  # 建议只保存密钥，不要存 token 全文
      expiration: 7200  # 单位：秒

    cors:
      enable: true
      allowedOrigins:
        - "http://localhost:9528"
        - "http://127.0.0.1:8080"
        - "http://kubeants-apiserver.kubeants-system"
        - "http://172.17.142.147:30001"
      defaultOrigins: "http://localhost:9528"  # 默认允许的 Origin，建议开发环境使用 localhost
      accessControlAllowCredentials: "true"
      accessControlAllowHeaders: "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id"
      accessControlAllowMethods: "POST, GET, OPTIONS, DELETE, PUT"
      accessControlExposeHeaders: "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, New-Token, New-Expires-At"
kind: ConfigMap
metadata:
  name: kubeants-apiserver
  namespace: kubeants-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeants-apiserver
  name: kubeants-apiserver
  namespace: kubeants-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeants-apiserver
  template:
    metadata:
      labels:
        app: kubeants-apiserver
    spec:
      securityContext:
        runAsUser: 0  # 以 root 用户运行
        runAsGroup: 0
      containers:
        - image: "registry.cn-hangzhou.aliyuncs.com/geray/kubeants-apiserver:v1.7.0"
          imagePullPolicy: IfNotPresent
          name: kubeants-apiserver
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /root/.kube/config
              subPath: config  # 如果 Secret 中只有一个 key，也可以省略 subPath，但推荐明确指定
            - name: kubeants-apiserver
              mountPath: /config.yaml
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      hostAliases:
        - ip: 172.17.142.147
          hostnames: 
            - lb.kubesphere.local
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig  # 这里替换为你的 Secret 的名字
        - name: kubeants-apiserver
          configMap:
            name: kubeants-apiserver
---
# 创建一个NodePort方式暴露的Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeants-apiserver
  name: kubeants-apiserver
  namespace: kubeants-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: kubeants-apiserver
  type: NodePort

