definitions:
  middleware.User:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /gapi/login:
    post:
      consumes:
      - application/json
      description: 验证用户输入的用户名和密码，如果正确，则返回 JWT。
      parameters:
      - description: 用户登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/middleware.User'
      produces:
      - application/json
      responses:
        "200":
          description: 登陆成功
          schema:
            additionalProperties: true
            type: object
      summary: '用户登录接口: 验证用户登录信息并返回 JWT。'
      tags:
      - 用户
  /gapi/user/info:
    get:
      consumes:
      - application/json
      description: 验证用户输入的用户名和密码，如果正确，则返回 JWT。
      produces:
      - application/json
      responses:
        "200":
          description: 登陆成功
          schema:
            additionalProperties: true
            type: object
      summary: 认证通过后返回用户信息。
      tags:
      - 用户
swagger: "2.0"
